version: '3.8'
services:
  leaderboard:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./leaderboard.db:/root/leaderboard.db
      - ./static:/root/static
    restart: unless-stopped